feat: login ui
nurulid/project-devwiz pull request #6
Opened 2023-11-28 12:07 UTC by anto1313

i have made ui login

2023-11-28 12:09 UTC, indrazm commented on src/app/(auth)/login/page.js
> +  return <main>
You don't need <main>. Please remove it.

2023-11-28 12:09 UTC, indrazm commented on src/app/page.js
> +  return <main>
You don't need <main>. Please remove it.

2023-11-28 12:09 UTC, indrazm requested changes
Good

2023-11-30 12:34 UTC, anto1313 commented on src/app/(auth)/login/page.js
> +  return <main>
remove the code or the file sir ?

2023-12-01 02:52 UTC, indrazm commented on src/app/(auth)/register/page.js
No need `<main>`

2023-12-01 04:28 UTC, nurulid approved these changes
Good

2023-12-01 10:07 UTC, merged